# Generated by Django 3.2.8 on 2021-11-21 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_candidate_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.vacancy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sv_file',
            field=models.BinaryField(null=True),
        ),
    ]
